local M = {}

M.READ_FAILED = "READ_FAILED"
M.ADDRESS_NULL = "ADDRESS_NULL"
M.ADDRESS_OVERFLOW = "ADDRESS_OVERFLOW"
M.CIRCULAR_LIST_TOO_LONG = "CIRCULAR_LIST_TOO_LONG"
M.VECTOR_INVALID_RANGE = "VECTOR_INVALID_RANGE"
M.VECTOR_MISALIGNED = "VECTOR_MISALIGNED"
M.VECTOR_TOO_LONG = "VECTOR_TOO_LONG"

return M
