return {
  READ_FAILED = 0,
  ADDRESS_NULL = 1,
  ADDRESS_OVERFLOW = 2,
  CIRCULAR_LIST_TOO_LONG = 3,
  STRING_TOO_LONG = 4,
  VECTOR_INVALID_RANGE = 5,
  VECTOR_MISALIGNED = 6,
  VECTOR_TOO_LONG = 7,
}
