local M = {}

M.READ_FAILED = "READ_FAILED"
M.ADDRESS_NULL = "ADDRESS_NULL"
M.ADDRESS_OVERFLOW = "ADDRESS_OVERFLOW"
M.LIST_TOO_LONG = "LIST_TOO_LONG"
M.LIST_UNEXPECTED_CYCLE = "LIST_UNEXPECTED_CYCLE"
M.LIST_UNEXPECTED_NULL = "LIST_UNEXPECTED_NULL"
M.PRIMITIVE_OUT_OF_BOUNDS = "PRIMITIVE_OUT_OF_BOUNDS"
M.VECTOR_INVALID_RANGE = "VECTOR_INVALID_RANGE"
M.VECTOR_MISALIGNED = "VECTOR_MISALIGNED"
M.VECTOR_TOO_LONG = "VECTOR_TOO_LONG"
M.ZSTRING_TOO_LONG = "ZSTRING_TOO_LONG"

return M
